/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Diseño;

/**
 *
 * @author leo_8
 */
public class JpNuevoUsuario extends javax.swing.JPanel {

    /**
     * Creates new form JpNuevoUsuario
     */
    public JpNuevoUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbidUsuario = new javax.swing.JLabel();
        lbNombresUsuario = new javax.swing.JLabel();
        lbApellidosUsuario = new javax.swing.JLabel();
        lbEmailUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdUsuario = new javax.swing.JTextField();
        txtNombreUsuario = new javax.swing.JTextField();
        txtApellidosUsuario = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtContraseñaU = new javax.swing.JTextField();
        comboBoxRol = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 255));
        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setMinimumSize(new java.awt.Dimension(760, 460));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NUEVO USUARIO");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 210, 50));

        lbidUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbidUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lbidUsuario.setText("ID:");
        add(lbidUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 20, 30));

        lbNombresUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNombresUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lbNombresUsuario.setText("Nombres:");
        add(lbNombresUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        lbApellidosUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbApellidosUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lbApellidosUsuario.setText("Apellidos:");
        add(lbApellidosUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        lbEmailUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbEmailUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lbEmailUsuario.setText("Email:");
        add(lbEmailUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 40, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 70, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Rol:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, -1, -1));

        txtIdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdUsuarioActionPerformed(evt);
            }
        });
        add(txtIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 340, 30));
        add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 340, 30));
        add(txtApellidosUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 340, 30));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 322, 340, 30));

        txtContraseñaU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaUActionPerformed(evt);
            }
        });
        add(txtContraseñaU, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 340, 30));

        comboBoxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Caja", "Administrador" }));
        comboBoxRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxRolActionPerformed(evt);
            }
        });
        add(comboBoxRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 150, 30));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Validar");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 110, 40));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Registrar");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 110, 40));

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Vaciar");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 110, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdUsuarioActionPerformed

    private void txtContraseñaUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaUActionPerformed

    private void comboBoxRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxRolActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxRol;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbApellidosUsuario;
    private javax.swing.JLabel lbEmailUsuario;
    private javax.swing.JLabel lbNombresUsuario;
    private javax.swing.JLabel lbidUsuario;
    private javax.swing.JTextField txtApellidosUsuario;
    private javax.swing.JTextField txtContraseñaU;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
